config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from account.views import RedirectToLoginView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectToLoginView.as_view(), name="redirect_to_login"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("newspaper/", include("newspaper.urls", namespace="newspaper")),
    path("account/", include("account.urls", namespace="account")),
]

newspaper/urls.py
from django.urls import path

from newspaper.views import (NewspaperCreateView, NewspaperDeleteView,
                             NewspaperDetailView, NewspaperListView,
                             NewspaperUpdateView, TopicCreateView,
                             TopicDeleteView, TopicDetailView, TopicListView,
                             TopicUpdateView)

app_name = "newspaper"

urlpatterns = [
    path("", NewspaperListView.as_view(), name="index"),
    path("<int:pk>/", NewspaperDetailView.as_view(), name="detail"),
    path("create/", NewspaperCreateView.as_view(), name="create"),
    path("<int:pk>/update/", NewspaperUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", NewspaperDeleteView.as_view(), name="delete"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path(
        "topics/update/<int:pk>/",
        TopicUpdateView.as_view(),
        name="update-topic",
    ),
    path(
        "topics/delete/<int:pk>/",
        TopicDeleteView.as_view(),
        name="delete-topic",
    ),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path("topics/<int:pk>/", TopicDetailView.as_view(), name="topic-detail"),
]

templates/includes/agency_system_form.html
{% load crispy_forms_filters %}
{% load static %}
<section class="bg-image" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; overflow: hidden;">
  <img src="{% static 'images/good_news_main_image/good_news_image.jpg' %}" alt="My image"
       style="width: 100%; height: 100%; position: absolute">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6 mx-auto">
          <div class="card mx-auto my-5" style="border-radius: 115px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Create an account</h2>
              <form method="post">
                {% csrf_token %}
                {{ form.media }}
                {{ form|crispy }}
                <div class="d-flex justify-content-center">
                  <button type="submit"
                          class="btn btn-success btn-block btn-lg gradient-custom-4 ">Register
                  </button>
                </div>
                <br>
                <p>Already registered? <a href="{% url 'login' %}">Login here </a></p>
              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

templates/includes/footer.html
<hr class="line">
<footer class="container" id="footer">
  <p class="float-right"><a href="#popular_topics" style="color: goldenrod"><strong>Back to top</strong></a></p>
  <p class="footer_text"><strong>&copy; 2024 Good News Agency </strong><span style="margin-left: 80px"><strong>Coded by</strong> <a
      style="color: goldenrod;" href="https://github.com/mwellick"><strong>Vadym Sulim</strong></a></span>
  </p>
</footer>

templates/includes/navigation_bar.html
<header>
  <nav class="navbar navbar-expand-md  fixed-top  nav-bar">
    <div class="navbar-brand logo"><strong>GOOD</strong><strong> NEWS</strong></div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active justify-content-center">
          <a class="nav-link" href={% url 'newspaper:index' %}>Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Content</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Latest News</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About Us</a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        {% if user.is_authenticated %}
          <a class="btn btn-outline-success my-2 my-sm-0 btn-logout" href="{% url 'logout' %}">
            <i class="fa fa-sign-out me-1"></i> Logout
          </a>
        {% else %}
          <a class="btn btn-outline-success my-2 my-sm-0 btn-login" href="{% url 'login' %}">
            <i class="fa fa-sign-in me-1"></i> Login
          </a>
        {% endif %}
      </form>

    </div>
  </nav>
</header>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <br>
  <ul class="pagination justify-content-center pagination-lg">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" style="color: goldenrod;border: none"
           href="?{% query_transform request page=page_obj.previous_page_number %}">Prev</a>
      </li>
    {% endif %}
    <li class="page-item active"><span
        class="page-link"
        style="background-color: goldenrod; border: none">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" style="color: goldenrod;border: none"
           href="?{% query_transform request page=page_obj.next_page_number %}">Next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}