account/urls.py
from django.urls import path

from account.views import RedactorListView, SignupView, UpdateRedactorView

app_name = "account"

urlpatterns = [
    path("redactors/", RedactorListView.as_view(), name="redactor_list"),
    path("signup/", SignupView.as_view(), name="signup"),
    path(
        "update/<int:pk>", UpdateRedactorView.as_view(), name="redactor-update"
    ),
]

config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from account.views import RedirectToLoginView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectToLoginView.as_view(), name="redirect_to_login"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("newspaper/", include("newspaper.urls", namespace="newspaper")),
    path("account/", include("account.urls", namespace="account")),
]

newspaper/urls.py
from django.urls import path

from newspaper.views import (NewspaperCreateView, NewspaperDeleteView,
                             NewspaperDetailView, NewspaperListView,
                             NewspaperUpdateView, TopicCreateView,
                             TopicDeleteView, TopicDetailView, TopicListView,
                             TopicUpdateView)

app_name = "newspaper"

urlpatterns = [
    path("", NewspaperListView.as_view(), name="index"),
    path("<int:pk>/", NewspaperDetailView.as_view(), name="detail"),
    path("create/", NewspaperCreateView.as_view(), name="create"),
    path("<int:pk>/update/", NewspaperUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", NewspaperDeleteView.as_view(), name="delete"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path(
        "topics/update/<int:pk>/",
        TopicUpdateView.as_view(),
        name="update-topic",
    ),
    path(
        "topics/delete/<int:pk>/",
        TopicDeleteView.as_view(),
        name="delete-topic",
    ),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path("topics/<int:pk>/", TopicDetailView.as_view(), name="topic-detail"),
]

newspaper/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Topics"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE, related_name="newspapers"
    )
    publishers = models.ManyToManyField(
        get_user_model(), related_name="newspapers"
    )

    def __str__(self):
        return f"{self.title} - {self.published_date}"

newspaper/forms.py
from django import forms


class NewsSearchForm(forms.Form):
    username = forms.CharField(
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"}),
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"}),
    )

newspaper/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from newspaper.forms import NewsSearchForm, TopicSearchForm
from newspaper.models import Newspaper, Topic


class NewspaperListView(generic.ListView):
    model = Newspaper
    queryset = Newspaper.objects.all().order_by("-published_date")

    def get_queryset(self):
        queryset = super().get_queryset()
        title = self.request.GET.get('username')
        if title:
            queryset = queryset.filter(title__icontains=title)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = NewsSearchForm(self.request.GET)
        return context


class NewspaperDetailView(generic.DetailView):
    model = Newspaper


class NewspaperCreateView(generic.CreateView):
    model = Newspaper
    fields = "__all__"
    success_url = reverse_lazy("newspaper:index")


class NewspaperUpdateView(generic.UpdateView):
    model = Newspaper
    fields = "__all__"
    success_url = reverse_lazy("newspaper:index")


class NewspaperDeleteView(generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newspaper:index")


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")
    template_name = "newspaper/topic_form.html"


class TopicListView(generic.ListView):
    model = Topic

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get('name')
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = TopicSearchForm(self.request.GET)
        return context

class TopicDetailView(LoginRequiredMixin, generic.DetailView):
    model = Topic
    context_object_name = "topic"


class TopicUpdateView(generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicDeleteView(generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newspaper:topic-list")

templates/newspaper/newspaper_confirm_delete.html
{% extends "layouts/base.html" %}
{% block title %}
  <title>News Delete Confirmation</title>
{% endblock %}
{% block content %}
  <div class="container-fluid mt-5 d-flex flex-column justify-content-center align-items-center vh-100">
    <h1 style="color: goldenrod">Delete Article "{{ newspaper.title }}"</h1>
    <p><strong>Are you sure you want to delete this article ?</strong></p>
    <form action="" method="post">
      {% csrf_token %}
      <input type="submit" value="Yes, delete" class="btn btn-success btn_confirm"/>
      <a href="{% url 'newspaper:detail' pk=newspaper.id %}"
         class="btn btn-primary btn_confirm">Cancel</a>
    </form>
  </div>

{% endblock %}
{% block footer %}
{% endblock %}

templates/newspaper/newspaper_detail.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %}
  <title>{{ newspaper.title }}</title>
{% endblock %}
{% block navbar %}
  <header>
    <nav class="navbar navbar-expand-md  fixed-top  nav-bar">
      <div class="navbar-brand logo"><strong>Best</strong><strong> NEWS</strong></div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
              aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'newspaper:index' %}>Home</a>
          </li>
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'newspaper:topic-list' %}>All Topics</a>
          </li>
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'account:redactor_list' %}>All Redactors</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          {% if user.is_authenticated %}
            <a class="btn btn-outline-success my-2 my-sm-0 btn-logout" href="{% url 'logout' %}">
              <i class="fa fa-sign-out me-1"></i> Logout
            </a>
          {% else %}
            <a class="btn btn-outline-success my-2 my-sm-0 btn-login" href="{% url 'login' %}">
              <i class="fa fa-sign-in me-1"></i> Login
            </a>
          {% endif %}
        </form>

      </div>
    </nav>
  </header>
{% endblock %}
{% block content %}
  <div class="container mx-auto" style="padding-top: 7%">
  <br>

  <div class="container" style="color: white;">
    <h1 class="text-center" style="color: goldenrod">{{ newspaper.title }}</h1>
    <br>
    <div class="container">
      <p class="mb-2">
        {% if newspaper.publishers.all %}
          <strong
              style="color: goldenrod">By:</strong> {{ newspaper.publishers.all|join:", " }}</p>
        {% endif %}

      {% if newspaper.topic.all %}
        <p class="mb-2"><strong style="color: goldenrod">Topics:</strong>
          {{ newspaper.topic.all|join:", " }}
        </p>
      {% endif %}
      <p class="mb-2"><strong style="color: goldenrod">Published date:</strong> {{ newspaper.published_date }}</p>
      {% if newspaper.news_images %}
        <img class="news_image img-thumbnail text-center"
             src="{{ newspaper.news_images.url }}">
        <br>
      {% endif %}
      <br>
      {{ newspaper.content|safe }}
    </div>
    <div class="text-center">
      <br>
      {% if user.is_superuser or user.id == publisher.id %}
        <a href="{% url 'newspaper:update' pk=newspaper.id %}" class="btn btn-success topic-btn">Edit
          this article</a>
        <a href="{% url 'newspaper:delete' pk=newspaper.id %}" class=" btn btn-danger delete-btn"
           style="border-radius: 20px">Delete this article</a>
      {% endif %}
    </div>
    <br>
    <br>
  <div class="d-flex justify-content-center" style="font-size: 20px">
    <a class="btn btn-primary pl-2" style="border-radius: 20px"
       href="{% url 'newspaper:index' %}"> <-- Return to News list</a>
  </div>
  <br><br>
{% endblock %}
{% block footer %}
{% endblock %}


templates/newspaper/newspaper_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% block title %}
  <title>All News</title>
{% endblock %}
{% block navbar %}
  <header>
    <nav class="navbar navbar-expand-md  fixed-top  nav-bar">
      <div class="navbar-brand logo"><strong>Best</strong><strong> NEWS</strong></div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
              aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'newspaper:index' %}>Home</a>
          </li>
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'newspaper:topic-list' %}>All Topics</a>
          </li>
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'account:redactor_list' %}>All Redactors</a>
          </li>
        </ul>
          {% if user.is_authenticated %}
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <i class="fa fa-sign-out me-1"></i> <input class="btn btn-logout" type="submit" value="Logout">
            </form>
          {% else %}
            <a class="btn btn-outline-success my-2 my-sm-0 btn-login" href="{% url 'login' %}">
              <i class="fa fa-sign-in me-1"></i> Login
            </a>
          {% endif %}
      </div>
    </nav>
  </header>
{% endblock %}
{% block content %}
  <div class="container-fluid mt-5" style="padding-top: 2%">
    <div class="d-flex justify-content-between align-items-center mt-3">
      <h1 class="text-center" style="color: goldenrod; margin-right: 55px; font-size: 60px"><strong>News</strong>
      </h1>
      <a href="{% url 'newspaper:create' %}" class="btn btn-primary topic-btn">Add News</a>
    </div>
    <br>
    <form method="get" action="" class="form-multiline justify-content-center"
          style="max-height: 38px;max-width: 280px;">
      <div class="input-group">
        {{ search_form|crispy }}
        <button id="search-button"
                style="max-height: 38px; margin-left: 5px; background: transparent; color: goldenrod" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </form>
    <div class="row">
      {% if newspaper_list %}
        {% for article in  newspaper_list %}
          <div class="col-md-5 mb-5">
            <div class="card-content">
              <div class="card-content-body">
                <a href={% url 'newspaper:detail' pk=article.id %}>{{ article.title }}</a>
              </div>
            </div>
          </div>
        {% endfor %}
      {% elif search_form.title and search_form.title not in  newspaper_list %}
        <div class="container-fluid d-flex flex-column justify-content-center" style="margin-top: 200px;">
          <p class="text-center" style="color: goldenrod; font-size: 30px">
            <strong>No news found for your search</strong>
          </p>
        </div>
      {% else %}
        <div class="container-fluid d-flex flex-column justify-content-center" style="margin-top: 200px;">
          <p class="text-center" style="color: goldenrod; font-size: 30px">
            <strong>There are no news in Good News Agency.</strong>
          </p>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/newspaper/redactor_detail.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %}
  <title>Account Details</title>
{% endblock %}
{% block navbar %}
  <header>
    <nav class="navbar navbar-expand-md  fixed-top  nav-bar">
      <div class="navbar-brand logo"><strong>Best</strong><strong> NEWS</strong></div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
              aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'newspaper:index' %}>Home</a>
          </li>
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'account:redactor_list' %}>All Redactors</a>
          </li>
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href="{% url 'newspaper:topic-list' %}">All Topics</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          {% if user.is_authenticated %}
            <a class="btn btn-outline-success my-2 my-sm-0 btn-logout" href="{% url 'logout' %}">
              <i class="fa fa-sign-out me-1"></i> Logout
            </a>
          {% else %}
            <a class="btn btn-outline-success my-2 my-sm-0 btn-login" href="{% url 'login' %}">
              <i class="fa fa-sign-in me-1"></i> Login
            </a>
          {% endif %}
        </form>

      </div>
    </nav>
  </header>
{% endblock %}
{% block content %}
  <div class="container text-center" style="padding-top: 5%">
    <br>
    <div class="newspaper-box text-center " style="color: white">
      <h1 style="color: goldenrod">{{ redactor.first_name }} {{ redactor.last_name }}
      </h1>
      {% if  user.id == user.is_superuser or user.id == redactor.id %}
        <br>
        <a href="{% url 'account:redactor_list' %}" class=" btn-danger"
           style="border-radius: 20px; padding: 5px 10px; text-decoration: none;">Delete account</a>
        <br>
      {% endif %}
      <br>
      <h3><strong>Personal information</strong></h3>
      <br><br>
      <p><strong style="color: goldenrod">First name:</strong> {{ redactor.first_name }}</p>
      <p><strong style="color: goldenrod">Last name:</strong> {{ redactor.last_name }}</p>
      <p><strong style="color: goldenrod">Username:</strong> {{ redactor.username }}</p>
      {% if user.id == redactor.id %}
        <p><strong style="color: goldenrod">Password:</strong> ********
      {% endif %}
{#      {% if user.id == redactor.id %}#}
{#        <a class="ml-3" style="font-size: 1.3rem; text-decoration: none;"#}
{#           href="{% url 'agency_system:password-update' pk=redactor.id %}">Change#}
{#          Password</a>#}
{#      {% endif %}#}
      </p>
      {% if not redactor.bio %}
        <p><strong style="color: goldenrod">Bio:</strong> No bio yet</p>
      {% else %}
        <p><strong style="color: goldenrod">Bio:</strong>{{ redactor.bio }}</p>
      {% endif %}
      <p><strong style="color: goldenrod">Email:</strong> {{ redactor.email }}
        {% if not redactor.email %}
          No information given.
        {% endif %}
      </p>
      <p><strong style="color: goldenrod">Years of experience:</strong> {{ redactor.years_of_experience }}</p>
      <p><strong style="color: goldenrod">Author of newspapers:</strong>

        {% if  redactor.published_newspapers.count == 0 and user.id == redactor.id %}
          You have not published any news yet.
        {% endif %}
        {% if user.id != redactor.id and  redactor.published_newspapers.count == 0 %}
          This user has not published any news yet.
        {% elif redactor.published_newspapers.count > 0 %}
          {{ redactor.published_newspapers.count }}
        {% endif %}
      </p>
      <ol style="color: goldenrod">

        {% for newspaper in redactor.published_newspapers.all %}
          <li>
            <p style="font-size: 1.3rem">
              <a href="{% url 'agency_system:newspaper-detail' pk=newspaper.id %}" style="color: white">
                {{ newspaper.title }}
              </a>
            </p>
          </li>
        {% endfor %}
      </ol>
      <br>
      <div class="d-flex justify-content-center">
        {% if user.is_superuser %}
          <a href="{% url 'account:redactor-update' pk=redactor.id %}"
             class="btn btn-primary topic-btn text-center">Edit Profile</a>
        {% elif user.id == redactor.id %}
          <a href="{% url 'account:redactor-update' pk=redactor.id %}"
             class="btn btn-primary topic-btn text-center">Edit Profile</a>
        {% endif %}
      </div>
      <br>
    </div>
  </div>
{% endblock %}
{% block footer %}
{% endblock %}

templates/newspaper/redactor_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% block title %}
  <title>Redactors</title>
{% endblock %}
{% block navbar %}
  <header>
    <nav class="navbar navbar-expand-md  fixed-top  nav-bar">
      <div class="navbar-brand logo"><strong>Best</strong><strong> NEWS</strong></div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
              aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'newspaper:index' %}>Home</a>
          </li>
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'newspaper:topic-list' %}>All Topics</a>
          </li>
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'account:redactor_list' %}>All Redactors</a>
          </li>
        </ul>
          {% if user.is_authenticated %}
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <i class="fa fa-sign-out me-1"></i> <input class="btn btn-logout" type="submit" value="Logout">
            </form>
          {% else %}
            <a class="btn btn-outline-success my-2 my-sm-0 btn-login" href="{% url 'login' %}">
              <i class="fa fa-sign-in me-1"></i> Login
            </a>
          {% endif %}
      </div>
    </nav>
  </header>
{% endblock %}
{% block content %}
  <div class="container-fluid mt-5" style="padding-top: 2%">
    <div class="d-flex justify-content-between align-items-center mt-3">
      <h1 class="text-center" style="color: goldenrod; margin-right: 55px; font-size: 60px"><strong>Redactors</strong>
      </h1>
    </div>
    <br>
    <form method="get" action="" class="form-multiline justify-content-center"
          style="max-height: 38px;max-width: 280px;">
      <div class="input-group">
        {{ search_form|crispy }}
        <button id="search-button"
                style="max-height: 38px; margin-left: 5px; background: transparent; color: goldenrod" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </form>
    <div class="row">
      {% if redactor_list %}
        {% for redactor in  redactor_list %}
          <div class="col-md-5 mb-5">
            <div class="card-content" style="height: 150px;padding-top: 20px">
              <div class="card-content-body">
                <a href="{% url 'account:redactor-update' pk=redactor.pk %}">{{ redactor.username }}</a>
              </div>
            </div>
          </div>
        {% endfor %}
      {% elif search_form.username and search_form.username not in  redactor_list %}
        <div class="container-fluid d-flex flex-column justify-content-center" style="margin-top: 200px;">
          <p class="text-center" style="color: goldenrod; font-size: 30px">
            <strong>No users found for your search</strong>
          </p>
        </div>
      {% else %}
        <div class="container-fluid d-flex flex-column justify-content-center" style="margin-top: 200px;">
          <p class="text-center" style="color: goldenrod; font-size: 30px">
            <strong>There are no users in Best News Agency.</strong>
          </p>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}
{% block footer %}
{% endblock %}

templates/newspaper/topic_detail.html
{% extends "layouts/base.html" %}
{% block title %}
  <title>{{ topic.name }} Topic</title>
{% endblock %}
{% block navbar %}
  <header>
    <nav class="navbar navbar-expand-md  fixed-top  nav-bar">
      <div class="navbar-brand logo"><strong>Best</strong><strong> NEWS</strong></div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
              aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'newspaper:index' %}>Home</a>
          </li>
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'newspaper:topic-list' %}>All Topics</a>
          </li>
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'account:redactor_list' %}>All Redactors</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          {% if user.is_authenticated %}
            <a class="btn btn-outline-success my-2 my-sm-0 btn-logout" href="{% url 'logout' %}">
              <i class="fa fa-sign-out me-1"></i> Logout
            </a>
          {% else %}
            <a class="btn btn-outline-success my-2 my-sm-0 btn-login" href="{% url 'login' %}">
              <i class="fa fa-sign-in me-1"></i> Login
            </a>
          {% endif %}
        </form>

      </div>
    </nav>
  </header>
{% endblock %}
{% block content %}
  <div class="container-fluid" style="padding-top: 5%">
    <div class="d-flex justify-content-between align-items-center mt-3 mb-5">
      <h1 class="text-center" style="color: goldenrod; margin-right: 55px; font-size: 60px">
        <strong>{{ topic.name }}</strong>
      </h1>
      <div class="ml-auto">
        {% if user.id == user.is_superuser %}
          <a href="{% url 'newspaper:update-topic' pk=topic.id %}" class="btn btn-primary primary-btn mr-3"
             style="text-decoration: none;border-radius: 20px;">Edit topic</a>
          <a href="{% url 'newspaper:delete-topic' pk=topic.id %}" class="btn btn-danger delete-btn"
             style="text-decoration: none;">Delete topic</a>
        {% endif %}
      </div>
    </div>
    <br>
    <div class="row">
      {% if topic.newspapers.all %}
        {% for newspaper in  topic.newspapers.all %}
          <div class="col-md-5 mb-5">
            <div class="card-content" style="height: 150px; padding-top:5px;">
              <div class="card-content-body">
                <p style="font-size: 2.0rem"><a
                    href="{% url 'newspaper:detail' pk=newspaper.id %}">{{ newspaper.title }}</a></p>
              </div>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <div class="container-fluid d-flex flex-column justify-content-center" style="margin-top: 200px;">
          <p class="text-center" style="color: goldenrod; font-size: 30px"><strong>There are no news with this
            topic.</strong></p>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}
{% block footer %}
{% endblock %}

templates/newspaper/topic_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% block title %}
  <title>Topics</title>
{% endblock %}
{% block navbar %}
  <header>
    <nav class="navbar navbar-expand-md  fixed-top  nav-bar">
      <div class="navbar-brand logo"><strong>Best</strong><strong> NEWS</strong></div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
              aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'newspaper:index' %}>Home</a>
          </li>
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'newspaper:topic-list' %}>All Topics</a>
          </li>
          <li class="nav-item active justify-content-center">
            <a class="nav-link" href={% url 'account:redactor_list' %}>All Redactors</a>
          </li>
        </ul>
          {% if user.is_authenticated %}
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <i class="fa fa-sign-out me-1"></i> <input class="btn btn-logout" type="submit" value="Logout">
            </form>
          {% else %}
            <a class="btn btn-outline-success my-2 my-sm-0 btn-login" href="{% url 'login' %}">
              <i class="fa fa-sign-in me-1"></i> Login
            </a>
          {% endif %}
      </div>
    </nav>
  </header>
{% endblock %}
{% block content %}
  <div class="container-fluid" style="padding-top: 4%">
    <div class="d-flex  align-items-center mt-3">
      <h1 class="text-center" style="color: goldenrod; margin-right: 55px; font-size: 60px"><strong>Topics</strong>
      </h1>
      <a href="{% url 'newspaper:topic-create' %}" class="btn btn-primary topic-btn ml-auto"
         style="text-decoration: none;">Add a new topic</a>
    </div>
    <br>
    <form method="get" action="" class="form-multiline justify-content-center"
          style="max-height: 38px;max-width: 280px;">
      <div class="input-group">
        {{ search_form|crispy }}
        <button id="search-button"
                style="max-height: 38px; margin-left: 5px; background: transparent; color: goldenrod" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </form>
  </div>


  <br>
  <div class="row">
    {% if topic_list %}
      {% for topic in  topic_list %}
        <div class="col-md-5 mb-5">
          <div class="card-content" style="height: 150px;padding-top: 20px">
            <div class="card-content-body">
              <a href="{% url 'newspaper:topic-detail' pk=topic.id %}">{{ topic.name }}</a>
            </div>
          </div>
        </div>
      {% endfor %}
    {% elif search_form.name and search_form.name not in  topic_list %}
      <div class="container-fluid d-flex flex-column justify-content-center" style="margin-top: 200px;">
        <p class="text-center" style="color: goldenrod; font-size: 30px">
          <strong>No topics found for your search</strong>
        </p>
      </div>
    {% else %}
      <div class="container-fluid d-flex flex-column justify-content-center" style="margin-top: 200px;">
        <p class="text-center" style="color: goldenrod; font-size: 30px">
          <strong>There are no topics in Good News Agency.</strong>
        </p>
      </div>
    {% endif %}
  </div>
{% endblock %}

{% block footer %}
{% endblock %}